# Используем официальный образ PostgreSQL
FROM postgres:latest

# Устанавливаем переменные среды для базы данных
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase

# Открываем порт PostgreSQL
EXPOSE 5432
